name: Build- and Release LaTeX paper

on: [push]

jobs:
  build_latex:
    name: Compile LaTeX
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: './docs'
          root_file: document.tex
  release_latex:
    name: Create Release
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: './docs/document.pdf'

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./docs/document.pdf
          asset_name: document.pdf
          tag: ${{ github.ref }}
          overwrite: true
