name: Publish F# Nerddeck

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [win-x64, linux-x64, osx-x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Publish F#
        run: dotnet publish --configuration Release --self-contained true --runtime ${{ matrix.os }} --property:OutputPath=./publish/${{ matrix.os }}
        working-directory: ${{ github.workspace }}/fsharp/NerdDeckFSharp/src/App

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: NerdDeckFSharp-${{ matrix.os }}
          path: ${{ github.workspace }}/fsharp/NerdDeckFSharp/src/App/publish/${{ matrix.os }}
